# Generated by Django 3.1.5 on 2021-01-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeWebbApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('leaf_image_url', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
