# Generated by Django 3.1.5 on 2021-01-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeWebbApp', '0002_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='tree_image_url',
            field=models.ImageField(default='', upload_to='siteImages/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tree',
            name='leaf_image_url',
            field=models.ImageField(upload_to='siteImages/'),
        ),
    ]
